/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfacesGraficas;

import AccesoDatos.JDBC.*;
import AccesoDatos.Serializar.*;
import Modelo.Garaje;
import Modelo.Motocicleta;
import Modelo.MotocicletaExcepcion;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author victo
 */
public class ModificarMoto_Grafico extends javax.swing.JFrame {

    //Movimiento JPanel
    private static int mouseX, mouseY;
    private static boolean mousePressed;
    // Atributos clase
    private String tipoPers;
    private Motocicleta moto;
    private JDBCGarajeDAO garajeDAO;
    private JDBCMotocicletaDAO motoDAO;
    private SerializarGarajeDAO serialGaraje;
    private SerializarMotocicletaDAO serialMoto;

    //
    /**
     * Creates new form ModificarMoto_Grafico
     */
    public ModificarMoto_Grafico() {
        initComponents();
    }

    public ModificarMoto_Grafico(Motocicleta moto, Connection con_e, String tipoPers_e) {

        if (tipoPers_e.equals(Enumerados.metodoPersistencia.JDBC.toString())) {
            motoDAO = (JDBCMotocicletaDAO) Factorias.FactoriaDAO.crearObjetoDAO(Enumerados.tipoDAO.JDBC_MOTOCICLETA.toString(), con_e);
            garajeDAO = (JDBCGarajeDAO) Factorias.FactoriaDAO.crearObjetoDAO(Enumerados.tipoDAO.JDBC_GARAJE.toString(), con_e);
        } else {
            serialMoto = (SerializarMotocicletaDAO) Factorias.FactoriaDAO.crearObjetoDAO(Enumerados.tipoDAO.SERIALIZAR_MOTOCICLETA.toString());
            serialGaraje = (SerializarGarajeDAO) Factorias.FactoriaDAO.crearObjetoDAO(Enumerados.tipoDAO.SERIALIZAR_GARAJE.toString());
        }

        this.moto = moto;
        this.tipoPers = tipoPers_e;

        initComponents();
        cargarInfoMoto();
        habilitarArrastre(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        L_motosave_AgregarMoto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        L_matricula_ModificarMoto = new javax.swing.JLabel();
        L_Color_ModificarMoto = new javax.swing.JLabel();
        L_CC_ModificarMoto = new javax.swing.JLabel();
        B_volver_ModificarMoto = new javax.swing.JButton();
        B_Modificar_ModificarMoto = new javax.swing.JButton();
        TF_matricula_ModificarMoto = new javax.swing.JTextField();
        TF_CC_ModificarMoto = new javax.swing.JTextField();
        CB_color_ModificarMoto = new javax.swing.JComboBox<>();
        L_precio_ModificarMoto = new javax.swing.JLabel();
        TF_precio_ModificarMoto = new javax.swing.JTextField();
        L_sucursal_ModificarMoto = new javax.swing.JLabel();
        ChB_rematricular_ModificarMoto = new javax.swing.JCheckBox();
        CB_sucursal_ModificarMoto = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        L_Marca_modificarMoto = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        L_Modelo_modificarMoto = new javax.swing.JLabel();
        S_separador_Inicio = new javax.swing.JSeparator();
        E = new javax.swing.JLabel();
        cc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        L_motosave_AgregarMoto.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        L_motosave_AgregarMoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_motosave_AgregarMoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Drawable/MotoSave.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(L_motosave_AgregarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(L_motosave_AgregarMoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        L_matricula_ModificarMoto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        L_matricula_ModificarMoto.setText("Matricula:");

        L_Color_ModificarMoto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        L_Color_ModificarMoto.setText("Color:");

        L_CC_ModificarMoto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        L_CC_ModificarMoto.setText("Cilindrada:");

        B_volver_ModificarMoto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        B_volver_ModificarMoto.setText("Volver");
        B_volver_ModificarMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_volver_ModificarMotoActionPerformed(evt);
            }
        });

        B_Modificar_ModificarMoto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        B_Modificar_ModificarMoto.setText("Modificar");
        B_Modificar_ModificarMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Modificar_ModificarMotoActionPerformed(evt);
            }
        });

        TF_matricula_ModificarMoto.setEditable(false);

        CB_color_ModificarMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_color_ModificarMotoActionPerformed(evt);
            }
        });

        L_precio_ModificarMoto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        L_precio_ModificarMoto.setText("Precio:");

        L_sucursal_ModificarMoto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        L_sucursal_ModificarMoto.setText("Sucursal:");

        ChB_rematricular_ModificarMoto.setText("Rematricular");
        ChB_rematricular_ModificarMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChB_rematricular_ModificarMotoActionPerformed(evt);
            }
        });

        jLabel7.setText("Marca:");

        L_Marca_modificarMoto.setText("Honda");

        jLabel8.setText("Modelo:");

        L_Modelo_modificarMoto.setText("CBR");

        S_separador_Inicio.setForeground(new java.awt.Color(204, 204, 204));

        E.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        E.setText("€");

        cc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cc.setText("Cc");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(B_volver_ModificarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(B_Modificar_ModificarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(S_separador_Inicio)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_Color_ModificarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_matricula_ModificarMoto)
                            .addComponent(L_CC_ModificarMoto)
                            .addComponent(L_sucursal_ModificarMoto)
                            .addComponent(L_precio_ModificarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CB_sucursal_ModificarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CB_color_ModificarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TF_matricula_ModificarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ChB_rematricular_ModificarMoto))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TF_precio_ModificarMoto)
                                    .addComponent(TF_CC_ModificarMoto, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(E, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(14, 14, 14)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L_Marca_modificarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_Modelo_modificarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_Marca_modificarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Modelo_modificarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(S_separador_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_sucursal_ModificarMoto)
                    .addComponent(CB_sucursal_ModificarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_matricula_ModificarMoto)
                    .addComponent(TF_matricula_ModificarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChB_rematricular_ModificarMoto))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_Color_ModificarMoto)
                    .addComponent(CB_color_ModificarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_CC_ModificarMoto)
                    .addComponent(TF_CC_ModificarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_precio_ModificarMoto)
                    .addComponent(TF_precio_ModificarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_volver_ModificarMoto)
                    .addComponent(B_Modificar_ModificarMoto))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_volver_ModificarMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_volver_ModificarMotoActionPerformed
        this.dispose();
    }//GEN-LAST:event_B_volver_ModificarMotoActionPerformed

    private void B_Modificar_ModificarMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Modificar_ModificarMotoActionPerformed
        String sucursal = (String) CB_sucursal_ModificarMoto.getSelectedItem();
        String matricula = "";
        String color = (String) CB_color_ModificarMoto.getSelectedItem();
        int cilindrada = 0;
        int precio = 0;

        // Control matricula
        if (!INTERFACES.Entradable.validarMatricula(TF_matricula_ModificarMoto.getText())) {
            JOptionPane.showMessageDialog(this, "La matricula no cumple con el formato requerido. Ej: 1234ABC", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            matricula = TF_matricula_ModificarMoto.getText();
        }

        // Control CC y Precio
        if (INTERFACES.Entradable.esInt(TF_CC_ModificarMoto.getText()) && INTERFACES.Entradable.esInt(TF_precio_ModificarMoto.getText())) {
            cilindrada = Integer.parseInt(TF_CC_ModificarMoto.getText());
            precio = Integer.parseInt(TF_precio_ModificarMoto.getText());
        } else {
            JOptionPane.showMessageDialog(this, "Solo puede introducir numeros en los campos 'CC' y 'Precio'.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        Motocicleta motoModificada = new Motocicleta(sucursal2Id(sucursal), matricula, moto.getMarca(), moto.getModelo(), color, cilindrada, precio);

        // Guardamos la moto dependiendo del tipo de persistencia que se haya seleccionado en el login.
        if (tipoPers.equals(Enumerados.tipoDAO.JDBC_MOTOCICLETA.toString())) {
            try {
                motoDAO.modificarMoto(motoModificada);
            } catch (MotocicletaExcepcion e) {
                JOptionPane.showMessageDialog(this, "No se ha podido moficar la motocicleta.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            try {
                serialMoto.modificarMoto(motoModificada);
            } catch (MotocicletaExcepcion e) {
                JOptionPane.showMessageDialog(this, "No se ha podido moficar la motocicleta.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        this.dispose();
    }//GEN-LAST:event_B_Modificar_ModificarMotoActionPerformed

    private void CB_color_ModificarMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_color_ModificarMotoActionPerformed

    }//GEN-LAST:event_CB_color_ModificarMotoActionPerformed

    private void ChB_rematricular_ModificarMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChB_rematricular_ModificarMotoActionPerformed
        if (TF_matricula_ModificarMoto.isEditable()) {
            TF_matricula_ModificarMoto.setEditable(false);
        } else {
            TF_matricula_ModificarMoto.setEditable(true);
        }
    }//GEN-LAST:event_ChB_rematricular_ModificarMotoActionPerformed

    private void cargarInfoMoto() {
        L_Marca_modificarMoto.setText(moto.getMarca());
        L_Modelo_modificarMoto.setText(moto.getModelo());
        cargarSucursales();
        TF_matricula_ModificarMoto.setText(moto.getMatricula());
        cargarColoresCB();
        TF_CC_ModificarMoto.setText(String.valueOf(moto.getCC()));
        TF_precio_ModificarMoto.setText(String.valueOf(moto.getPrecio()));
    }

    private void cargarColoresCB() {
        String[] colores_aux = {"Rojo", "Azul", "Verde", "Negro", "Blanco", "Gris", "Amarillo"};
        String colorMoto = moto.getColor();
        ArrayList<String> colores = new ArrayList();
        colores.add(colorMoto);
        for (int i = 0; i < colores_aux.length; i++) {
            if (!colores_aux[i].equals(colorMoto)) {
                colores.add(colores_aux[i]);
            }
        }
        for (String color : colores) {
            CB_color_ModificarMoto.addItem(color);
        }
    }

    // Devuelve un idGaraje dada una sucursal.
    private int sucursal2Id(String sucursal) {
        if (tipoPers.equals(Enumerados.metodoPersistencia.JDBC.toString())) {
            ArrayList<Garaje> garajes_aux = garajeDAO.listarGaraje();
            for (Garaje garaje : garajes_aux) {
                if (garaje.getSucursal().equals(sucursal)) {
                    return garaje.getIdGaraje();
                }
            }
        } else {
            ArrayList<Garaje> garajes_aux = serialGaraje.listarGaraje();
            for (Garaje garaje : garajes_aux) {
                if (garaje.getSucursal().equals(sucursal)) {
                    return garaje.getIdGaraje();
                }
            }
        }
        return 0;
    }

    // Carga primero la sucursal en la que se encuantra la moto y despues el resto.
    private void cargarSucursales() {
        ArrayList<String> sucursales = new ArrayList();
        ArrayList<Garaje> garajes_aux = null;
        
        if (tipoPers.equals(Enumerados.metodoPersistencia.JDBC.toString())) {
            garajes_aux = garajeDAO.listarGaraje();
        } else {
            garajes_aux = serialGaraje.listarGaraje();
        }
        
        for (Garaje garaje : garajes_aux) {
            if (garaje.getIdGaraje() == moto.getIdGaraje()) {
                sucursales.add(garaje.getSucursal());
            }
        }
        for (Garaje garaje : garajes_aux) {
            if (garaje.getIdGaraje() != moto.getIdGaraje()) {
                sucursales.add(garaje.getSucursal());
            }
        }
        for (String sucursal : sucursales) {
            CB_sucursal_ModificarMoto.addItem(sucursal);
        }
    }

    public static void habilitarArrastre(JFrame frame) {
        frame.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                mousePressed = true;
                mouseX = e.getX();
                mouseY = e.getY();
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                mousePressed = false;
            }
        });

        frame.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                if (mousePressed) {
                    int x = e.getXOnScreen();
                    int y = e.getYOnScreen();
                    frame.setLocation(x - mouseX, y - mouseY);
                }
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarMoto_Grafico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarMoto_Grafico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarMoto_Grafico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarMoto_Grafico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarMoto_Grafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Modificar_ModificarMoto;
    private javax.swing.JButton B_volver_ModificarMoto;
    private javax.swing.JComboBox<String> CB_color_ModificarMoto;
    private javax.swing.JComboBox<String> CB_sucursal_ModificarMoto;
    private javax.swing.JCheckBox ChB_rematricular_ModificarMoto;
    private javax.swing.JLabel E;
    private javax.swing.JLabel L_CC_ModificarMoto;
    private javax.swing.JLabel L_Color_ModificarMoto;
    private javax.swing.JLabel L_Marca_modificarMoto;
    private javax.swing.JLabel L_Modelo_modificarMoto;
    private javax.swing.JLabel L_matricula_ModificarMoto;
    private javax.swing.JLabel L_motosave_AgregarMoto;
    private javax.swing.JLabel L_precio_ModificarMoto;
    private javax.swing.JLabel L_sucursal_ModificarMoto;
    private javax.swing.JSeparator S_separador_Inicio;
    private javax.swing.JTextField TF_CC_ModificarMoto;
    private javax.swing.JTextField TF_matricula_ModificarMoto;
    private javax.swing.JTextField TF_precio_ModificarMoto;
    private javax.swing.JLabel cc;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
