/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package INTERFACES;

import AccesoDatos.JDBC.JDBCMotocicletaDAO;
import Modelo.Motocicleta;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;

/**
 *
 * @author David
 */
public class AgregarMoto_Grafico extends javax.swing.JFrame {

    //Movimiento JPanel
    private static int mouseX, mouseY;
    private static boolean mousePressed;
    // Atributos clase
    private int idGaraje;
    // Conexion y BDD
    private ConexionBBDD conexionbd = new ConexionBBDD();
    private Connection con = conexionbd.getCon();
    private JDBCMotocicletaDAO motocicletaDAO = new JDBCMotocicletaDAO(con);

    public AgregarMoto_Grafico() {
        initComponents();
        habilitarArrastre(this);
    }

    public AgregarMoto_Grafico(int idGaraje_e) {
        idGaraje = idGaraje_e;
        initComponents();
        String[] colores = {"Rojo", "Azul", "Verde", "Negro", "Blanco", "Gris", "Amarillo"};

        for (String color : colores) {
            CB_color_AgregarMoto.addItem(color);
        }
        habilitarArrastre(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        L_motosave_AgregarMoto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        L_infoAgregar_AgregarMoto = new javax.swing.JLabel();
        L_matricula_AgregarMoto = new javax.swing.JLabel();
        L_marca_AgregarMoto = new javax.swing.JLabel();
        L_modelo_AgregarMoto = new javax.swing.JLabel();
        L_Color_AgregarMoto = new javax.swing.JLabel();
        L_CC_AgregarMoto = new javax.swing.JLabel();
        B_volver_AgregarMoto = new javax.swing.JButton();
        B_Agregar_AgregarMoto = new javax.swing.JButton();
        TF_marca_AgregarMoto = new javax.swing.JTextField();
        TF_modelo_AgregarMoto = new javax.swing.JTextField();
        TF_matricula_AgregarMoto = new javax.swing.JTextField();
        TF_CC_AgregarMoto = new javax.swing.JTextField();
        CB_color_AgregarMoto = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        L_motosave_AgregarMoto.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        L_motosave_AgregarMoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_motosave_AgregarMoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Drawable/MotoSave.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(L_motosave_AgregarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(L_motosave_AgregarMoto, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );

        L_infoAgregar_AgregarMoto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        L_infoAgregar_AgregarMoto.setText("Introduce los siguientes datos:");

        L_matricula_AgregarMoto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        L_matricula_AgregarMoto.setText("Matricula:");

        L_marca_AgregarMoto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        L_marca_AgregarMoto.setText("Marca:");

        L_modelo_AgregarMoto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        L_modelo_AgregarMoto.setText("Modelo:");

        L_Color_AgregarMoto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        L_Color_AgregarMoto.setText("Color:");

        L_CC_AgregarMoto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        L_CC_AgregarMoto.setText("C.C:");

        B_volver_AgregarMoto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        B_volver_AgregarMoto.setText("Volver");
        B_volver_AgregarMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_volver_AgregarMotoActionPerformed(evt);
            }
        });

        B_Agregar_AgregarMoto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        B_Agregar_AgregarMoto.setText("Agregar");
        B_Agregar_AgregarMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Agregar_AgregarMotoActionPerformed(evt);
            }
        });

        CB_color_AgregarMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_color_AgregarMotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_infoAgregar_AgregarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(L_CC_AgregarMoto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(L_Color_AgregarMoto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(L_modelo_AgregarMoto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(L_marca_AgregarMoto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(L_matricula_AgregarMoto, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TF_CC_AgregarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CB_color_AgregarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TF_matricula_AgregarMoto, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(TF_marca_AgregarMoto)
                                    .addComponent(TF_modelo_AgregarMoto))))
                        .addContainerGap(71, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(B_volver_AgregarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(B_Agregar_AgregarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_infoAgregar_AgregarMoto)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_matricula_AgregarMoto)
                    .addComponent(TF_matricula_AgregarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_marca_AgregarMoto)
                    .addComponent(TF_marca_AgregarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_modelo_AgregarMoto)
                    .addComponent(TF_modelo_AgregarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_Color_AgregarMoto)
                    .addComponent(CB_color_AgregarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_CC_AgregarMoto)
                    .addComponent(TF_CC_AgregarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_volver_AgregarMoto)
                    .addComponent(B_Agregar_AgregarMoto))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CB_color_AgregarMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_color_AgregarMotoActionPerformed

    }//GEN-LAST:event_CB_color_AgregarMotoActionPerformed

    private void B_Agregar_AgregarMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Agregar_AgregarMotoActionPerformed

        // Controlar excepciones (que no sean null los textField). 
        // Hacer todos los campos obligatorios.
        if ((TF_matricula_AgregarMoto.getText().equals("")) || (TF_matricula_AgregarMoto.getText() == null)) {
            JOptionPane.showMessageDialog(this, "La matricula no puede estar vacia.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        // Verificar si la matrícula cumple formato
        if (!INTERFACES.Entradable.validarMatricula(TF_matricula_AgregarMoto.getText())) {
            JOptionPane.showMessageDialog(this, "La matricula no cumple con el formato requerido. Ej: 1234ABC", "Error", JOptionPane.ERROR_MESSAGE);
        }

        String Marca = null;
        String Modelo = null;
        String Color = (String) CB_color_AgregarMoto.getSelectedItem();
        int cilindrada = 0;

        //controlar que la marca, el modelo y la cilindrada no esten vacios
        if (TF_marca_AgregarMoto.getText().isEmpty() || TF_modelo_AgregarMoto.getText().isEmpty() || TF_CC_AgregarMoto.getText().isEmpty()) {

        } else {
            JOptionPane.showMessageDialog(this, "La marca no puede estas vacia", "Error", JOptionPane.ERROR_MESSAGE);
        }

        Marca = TF_marca_AgregarMoto.getText();
        Modelo = TF_modelo_AgregarMoto.getText();
        cilindrada = Integer.parseInt(TF_CC_AgregarMoto.getText());

        // Comprobar si la motocicleta ya existe
        if (motocicletaDAO.buscarMoto(TF_matricula_AgregarMoto.getText()) == null) {
            JOptionPane.showMessageDialog(this, "La motocicleta ya existe en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        // Falta meter el precio
//        Motocicleta newMoto = new Motocicleta(idGaraje, TF_matricula_AgregarMoto.getText(), Marca, Modelo, Color, cilindrada);
//        if (motocicletaDAO.altaMoto(newMoto)) {
//            JOptionPane.showMessageDialog(this, "La motocicleta se agrego exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
//        } else {
//            JOptionPane.showMessageDialog(this, "Error al agregar la motocicleta.", "Error", JOptionPane.ERROR_MESSAGE);
//        }


    }//GEN-LAST:event_B_Agregar_AgregarMotoActionPerformed

    private void B_volver_AgregarMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_volver_AgregarMotoActionPerformed
        this.dispose();
    }//GEN-LAST:event_B_volver_AgregarMotoActionPerformed

    public static void habilitarArrastre(JFrame frame) {
        frame.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                mousePressed = true;
                mouseX = e.getX();
                mouseY = e.getY();
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                mousePressed = false;
            }
        });

        frame.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                if (mousePressed) {
                    int x = e.getXOnScreen();
                    int y = e.getYOnScreen();
                    frame.setLocation(x - mouseX, y - mouseY);
                }
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarMoto_Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarMoto_Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarMoto_Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarMoto_Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarMoto_Grafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Agregar_AgregarMoto;
    private javax.swing.JButton B_volver_AgregarMoto;
    private javax.swing.JComboBox<String> CB_color_AgregarMoto;
    private javax.swing.JLabel L_CC_AgregarMoto;
    private javax.swing.JLabel L_Color_AgregarMoto;
    private javax.swing.JLabel L_infoAgregar_AgregarMoto;
    private javax.swing.JLabel L_marca_AgregarMoto;
    private javax.swing.JLabel L_matricula_AgregarMoto;
    private javax.swing.JLabel L_modelo_AgregarMoto;
    private javax.swing.JLabel L_motosave_AgregarMoto;
    private javax.swing.JTextField TF_CC_AgregarMoto;
    private javax.swing.JTextField TF_marca_AgregarMoto;
    private javax.swing.JTextField TF_matricula_AgregarMoto;
    private javax.swing.JTextField TF_modelo_AgregarMoto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
